matrix:
  include:
    - language: android
      dist: trusty
      jdk: oraclejdk8
      env:
        global:
          - NODE_VERSION=stable
      android:
        components:
          # Uncomment the lines below if you want to
          # use the latest revision of Android SDK Tools
          # - tools
          # - platform-tools

          # The SDK version used to compile your project
          - build-tools-29.0.2
          - android-29
          - tools
          - platform-tools
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
          - sys-img-x86-android-29
      before_install:
        - ./travisci/android-before-install.sh
      install:
        - ./travisci/android-install.sh
      script:
        - ./travisci/android-scripts.sh

    - language: objective-c
      os: osx
      osx_image: xcode11.4
      env:
        global:
          - NODE_VERSION=stable
      install:
        - source ./travisci/ios-install.sh
      script:
        - source ./travisci/ios-script.sh
