matrix:
  include:
    - language: android
      dist: trusty
      jdk: oraclejdk8
      env:
        global:
          - NODE_VERSION=stable
      android:
        components:
          - build-tools-29.0.2
          - android-29
          - tools
          - platform-tools
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
          - sys-img-x86-android-29
        licenses:
          - android-sdk-license-.+
          - google-gdk-license-.+
      before_install:
        - source ./travisci/android-before-install.sh
      install:
        - source ./travisci/android-install.sh
      script:
        - source ./travisci/android-scripts.sh

    - language: objective-c
      os: osx
      osx_image: xcode11.4
      env:
        global:
          - NODE_VERSION=stable
      install:
        - source ./travisci/ios-install.sh
      script:
        - source ./travisci/ios-script.sh
