- language: objective-c
  os: osx
  osx_image: xcode11.4
  env:
    global:
      - NODE_VERSION=stable
  install:
    - source ./travisci/ios-install.sh
  script:
    - source ./travisci/ios-script.sh